<?php

/**
 * @file
 * Contains custom_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\user\Entity\User;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_help().
 */
function maria_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_migrate module.
    case 'help.page.maria_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Code For Maria Consulting') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function maria_custom_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_contact_node_29_add_form' && isset($form['captcha'])) {
    $form['captcha']['#weight'] = -100;
  }
}

/**
 * Implements hook_theme().
 */
function maria_custom_theme($existing, $type, $theme, $path) {
  return [
    'maria_custom_service_block' => [
      'path' => drupal_get_path('module', 'maria_custom') . '/templates',
      'variables' => [
        'more_services' => [],
      ],
      'template' => 'maria-custom-service-block'
    ],
  ];
}

function maria_custom_views_pre_view(ViewExecutable $view, $display_id, array &$args) {

  if ($view->id() == 'taxonomy_term' && $display_id === 'page_1') {
    if ($taxonomy = \Drupal::routeMatch()->getParameter('taxonomy_term')) {
      $vocabularyId = $taxonomy->getVocabularyId();
      if ($vocabularyId == 'tags') {
        $options = array(
          'id' => 'area_text_custom',
          'table' => 'views',
          'field' => 'area_text_custom',
          'relationship' => 'none',
          'group_type' => 'none',
          'admin_label' => '',
          'empty' => TRUE,
          'tokenize' => FALSE,
          'content' => '<h2>Related Services</h2>',
          'plugin_id' => 'text_custom',
        );
        $view->setHandler('page_1', 'header', 'area_text_custom', $options);
      }
    }
  }

}

/**
 * Alter the username that is displayed for a user.
 * @see hook_user_format_name_alter()
 */
function maria_custom_user_format_name_alter(&$name, AccountInterface $account) {
  // Display the user's uid instead of name.
  if ($account instanceof User &&
    $account->hasField('field_first_name') &&
    $account->hasField('field_last_name')) {
    $name = t('@first_name @last_name',
      ['@first_name' => $account->field_first_name->value,
        '@last_name' => $account->field_last_name->value,
      ]);
  }
}
